### PR TITLE
Prevent error when Content-Type does not contain charset

### LINKED ISSUE #1: TypeError: Cannot read property '1' of null
While using the function getHTML or getText as described in the README.md I get the following error. I can only use the unformated ouput of the query.

```
TypeError: Cannot read property '1' of null
    at getContentPart (/home/norbert/tools/calponia/acceptance-tests/node_modules/mailhog/mailhog.js:72:50)
    at Object.getText (/home/norbert/tools/calponia/acceptance-tests/node_modules/mailhog/mailhog.js:100:14)
....
```

### PR DESCRIPTION
**Pull request by n0v1**
fixes #1 

I also fixed the test script that did not work anymore since the docker image has no sh binary due to https://github.com/blueimp/mailhog/commit/a3fc57464ea90653c378fa36bdd78bbd5689a6a3.

### CODE REVIEW

**Comment by n0v1** [comment]
@blueimp friendly ping

**Comment by srghma** [comment]
@n0v1 hi, you have changed permissions for test.js and test.sh from 100755 to 100644, now files are not executable, this is mistake

**Comment by srghma** [comment]
@n0v1 no worries, I've did it in https://github.com/blueimp/mailhog-node/pull/3

**Comment by n0v1** [comment]
@srghma thanks for the hint. I also fixed the permissions on my branch. (This was caused by my WSL config)

**Comment by blueimp** [comment]
Thanks for your contributions, @n0v1 and @srghma and sorry for the late reply.

I am on a longer holiday, but will check it and merge around next week.

**Review by blueimp — APPROVED** [review]

**Pull request merged**
