### PR TITLE
feat: deleteAll, getAll, refactoring

### PR DESCRIPTION
**Pull request by srghma**
this pr subsumes https://github.com/blueimp/mailhog-node/pull/2

### CODE REVIEW

**Comment by srghma** [comment]
@blueimp hi, what you think about this pr?

P.S. I will not refuse if you make me contributor for this project, it's hard to be the only one maintainer, I could review and merge pr's

**Comment by blueimp** [comment]
Hey @srghma, thanks for your contribution.

I'm not really interested in merging a complete refactoring without understanding the benefits this would provide.

If you would like to see a new feature added, it's much better to send it as an individual pull request with as few changes as possible.

**Comment by srghma** [comment]
@blueimp I've added babel to be able to use `async/await`

do I understand correctly that you don't want to see babel in this project?

**Comment by blueimp** [comment]
Yeah, although async/await is a really neat pattern, I don't see a need to update the code of an existing, working project.

**Comment by srghma** [comment]
@blueimp sorry to hear that, maybe someday you will change your mind

**Comment by srghma** [comment]
actually we can leave babel only for tests and for src/index.js use `require` instead of `import`

this will also fix issue with `now: require('mailhog').default, before: require('mailhog')` 

but let's leave eslint and prettier and new actions

**Comment by blueimp** [comment]
Please don't take my stance on this too hard, I always appreciate when someone takes the time to create a pull request for one of my projects, even if I reject it for some reason.

And to your previous mention of willing to maintain this project:
At the moment I think I can still handle the minimum maintenance required.

One thing you could do though is maintain your project as the modern javascript fork of this one and publish it to NPM - there might be other users out there that appreciate the refactored code.

**Comment by srghma** [comment]
but for real - tests should be implemented using some test framework like mocha or jest

**Comment by srghma** [comment]
> At the moment I think I can still handle the minimum maintenance required.


lot of api calls are missed, check https://github.com/SMenigat/cypress-mailhog/blob/master/index.js to see what is missing

**Comment by blueimp** [comment]
For this minimal project, making use of the assert module built into NodeJS serves its purpose in my view and doesn't require adding another dependency.
In fact, keeping the number of dependencies low is one of the goals I had for this project.

**Comment by srghma** [comment]
I mean it's good to add test framework because right now your test script tests all methods at once sequentially, for methods that are added to master right now - it's fine, but for more complicated cases, like `deleteAll` function - no

it's development dependencies, they don't mean much

**Comment by blueimp** [comment]
Hey @srghma,
I've released a new major version that adds new methods and covers the useful API endpoints for both MailHog v1/v2.
I've also used Mocha for unit testing as per your suggestion.
I still prefer to use a JS version that is supported by Node and doesn't require transpiling, so the code still uses require calls instead of JS module imports.

I think the new version addresses most of your concerns, so I'll close this pull request.
Please feel free to comment if you feel otherwise.

**Pull request closed without merging**
